apiVersion: v1
kind: Pod
metadata:
  name: vote-pod
  labels:
    app: vote-pod
spec:
  containers:
    - name: vote-pod
      image: kobesergio/final-project-vote:1.0
      ports:
      - containerPort: 5000