apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    app: worker-pod
spec:
  containers:
    - name: worker-pod
      image: kobesergio/final-project-worker:1.0
      ports:
      - containerPort: 5000